name: envelope_lite
description: "A clean, modern digital cash stuffing app."
publish_to: "none"

version: 1.0.8+9

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & utilities
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  flutter_speed_dial: ^7.0.0
  shared_preferences: ^2.3.2
  gap: ^3.0.1
  google_fonts: ^6.1.0  # ADD THIS LINE
  provider: ^6.0.5
  table_calendar: ^3.1.2



  # Firebase core packages (compatible with Flutter 3.9)
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  rxdart: ^0.28.0
  google_sign_in: ^6.2.1  
  package_info_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true