name: envelope_lite
description: "A clean, modern digital cash stuffing app."
publish_to: "none"

version: 1.1.1+2

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  flutter_speed_dial: ^7.0.0
  shared_preferences: ^2.3.2
  gap: ^3.0.1
  google_fonts: ^6.1.0
  provider: ^6.0.5
  table_calendar: ^3.1.2
  path_provider: ^2.1.0
  share_plus: ^7.2.0
  url_launcher: ^6.2.0
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  rxdart: ^0.28.0
  google_sign_in: ^6.2.1  
  package_info_plus: ^9.0.0
  fl_chart: ^0.66.0
  uuid: ^4.0.0
  # tutorial_coach_mark removed
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

# Configuration Block
flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/app_icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  
  # Assets Section
  assets:
    - assets/icon/app_icon.png
    - assets/sounds/